<?php
// Automatically Generated by TestLink Installer - Mon, 07 Apr 25 22:32:04 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.20.0.2');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
